### ISSUE TITLE
Ask for default app Brave android

### ISSUE THREAD

**Issue by Dirtyblckpistol** [brave/browser-android#682] opened 2016-02-03 22:37 UTC
Here is a problem that appeared on Android 6.0.1 HTC a9 

See image . When I open brave this is what happens
![screenshot_20160203-143151](https://cloud.githubusercontent.com/assets/16938671/12799413/975f40fc-ca83-11e5-8869-f17384703eee.png)

**Comment by Dirtyblckpistol** [comment] 2016-02-03 22:38
![screenshot_20160203-143753](https://cloud.githubusercontent.com/assets/16938671/12799457/c427bb64-ca83-11e5-9817-981392811d56.png)

**Comment by SergeyZhukovsky** [comment] 2016-02-04 17:30
Should be fixed in that commit
https://github.com/brave/browser-android/commit/7df1185886469adecd172f2f70cd32756fb983d2
The fix will appear on next release.
Thanks @Dirtyblckpistol, for posting an issue!

**Comment by Kessir** [comment] 2016-04-05 10:05
@SergeyZhukovsky hey, should this issue not be closed if the problem is  fixed?

**Comment by SergeyZhukovsky** [comment] 2016-04-05 10:08
Yes it should. Thanks for the reminder.

**Closed by SergeyZhukovsky** 2016-04-05 10:08 UTC
